version: '3.7'
services:
    sheriff:
        build: .
        container_name: "sheriff"
        volumes:
            - ./src:/app/src
        ports:
            - 8000:8000
        links:
            - mongodb
        depends_on:
            - mongodb
        command: python3 /app/src/scripts/populate_mongo.py
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        volumes: 
          - /data/db:/data/db
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/stdout # --quiet
